### ISSUE TITLE
Analizar y solucionar problema de autenticación de conexión a base de datos reportes de forma local 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#192]
Se debe analizar el problema de conexión entre la base de datos mongo y la herramienta  knowage, se debe realizar la búsqueda del problema de forma local para poder establece la conexión a una base que cuente con seguridad  de autenticación, la issue debe cumplir con los siguientes requerimientos:

- [x] Analizar el problema encontrado en la conexión entre la herramienta y la base 
- [ ] Solucionar el problema de conexión de forma local

**Comment by JoseAlejoGonza** [comment]
Existe un problema de conexión entre Knowage Report Design y MongoDB al crear un nuevo Data Source, se selecciona el tipo de base de datos MongoDB y enseguida a eso se ingresan los datos requeridos, los cuales son Host, Puerto, Nombre de la base de datos, Usuario y contraseña, todo de manera correcta, sin embargo no existe conexión dado que aparece el siguiente error:
![image](https://user-images.githubusercontent.com/25890828/152083415-4de092a4-4f31-4d0f-9fc0-841ead9f78de.png)

"_org.eclipse.datatools.connectivity.oda.OdaException ;
    com.mongodb.CommandResult$CommandFailure: command failed [authenticate]: { "serverUsed" : "mongotest.udistritaloas.edu.co/172.30.1.107:27017" , "ok" : 0.0 , "errmsg" : "Auth mechanism not specified" , "code" : 2 , "codeName" : "BadValue"}

	at org.eclipse.birt.data.oda.mongodb.impl.MDbConnection.authenticateDB(MDbConnection.java:210)

	at org.eclipse.birt.data.oda.mongodb.impl.MDbConnection.getMongoDatabase(MDbConnection.java:92)

	at org.eclipse.birt.data.oda.mongodb.impl.MDbConnection.open(MDbConnection.java:50)

	at org.eclipse.datatools.connectivity.oda.consumer.helper.OdaConnection.open(OdaConnection.java:250)

	at org.eclipse.datatools.connectivity.oda.profile.OdaConnectionWrapper.open(OdaConnectionWrapper.java:209)

	at org.eclipse.datatools.connectivity.oda.profile.OdaConnectionWrapper.<init>(OdaConnectionWrapper.java:59)

	at org.eclipse.datatools.connectivity.oda.profile.OdaConnectionFactory.createConnection(OdaConnectionFactory.java:26)

	at org.eclipse.datatools.connectivity.internal.ConnectionFactoryProvider.createConnection(ConnectionFactoryProvider.java:83)

	at org.eclipse.datatools.connectivity.internal.ConnectionProfile.createConnection(ConnectionProfile.java:359)

	at org.eclipse.datatools.connectivity.ui.PingJob.createTestConnection(PingJob.java:76)

	at org.eclipse.datatools.connectivity.oda.design.internal.ui.DataSourceEditorPageCore$1.run(DataSourceEditorPageCore.java:629)

	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)

	at org.eclipse.datatools.connectivity.ui.wizards.ProfileDetailsPropertyPage.testConnection(ProfileDetailsPropertyPage.java:98)

	at org.eclipse.datatools.connectivity.ui.wizards.ProfileDetailsPropertyPage$1.widgetSelected(ProfileDetailsPropertyPage.java:80)

	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)

	at org.eclipse.jface.window.Window.runEventLoop(Window.java:832)

	at org.eclipse.jface.window.Window.open(Window.java:808)

	at org.eclipse.birt.report.designer.ui.dialogs.BaseDialog.open(BaseDialog.java:111)

	at org.eclipse.birt.report.designer.data.ui.providers.EditableDataSourceNodeProvider.performEdit(EditableDataSourceNodeProvider.java:73)

	at org.eclipse.birt.report.designer.internal.ui.views.DefaultNodeProvider.performRequest(DefaultNodeProvider.java:472)

	at org.eclipse.birt.report.designer.internal.ui.views.actions.EditAction.doAction(EditAction.java:85)

	at org.eclipse.birt.report.designer.internal.ui.views.actions.AbstractElementAction.run(AbstractElementAction.java:70)

	at org.eclipse.birt.report.designer.internal.ui.views.RenameListener.doubleClick(RenameListener.java:214)

	at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:831)

	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)

	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)

	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:178)

	at org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java:828)

	at org.eclipse.jface.viewers.AbstractTreeViewer.handleDoubleSelect(AbstractTreeViewer.java:1472)

	at org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredViewer.java:1237)

	at org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:252)

	at org.eclipse.jface.util.OpenStrategy.access$0(OpenStrategy.java:249)

	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:311)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)

	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)

	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)

	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)

	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

Caused by: com.mongodb.CommandResult$CommandFailure: command failed [authenticate]: { "serverUsed" : "mongotest.udistritaloas.edu.co/172.30.1.107:27017" , "ok" : 0.0 , "errmsg" : "Auth mechanism not specified" , "code" : 2 , "codeName" : "BadValue"}

	at com.mongodb.CommandResult.getException(CommandResult.java:88)

	at com.mongodb.CommandResult.throwOnError(CommandResult.java:134)

	at com.mongodb.DB.authenticateCommand(DB.java:623)

	at org.eclipse.birt.data.oda.mongodb.impl.MDbConnection.authenticateDB(MDbConnection.java:199)

	... 63 more_"

La posible solución a dicho error podría ser actualizar el controlador jdbc de mongo dado que knowage por defecto no soporta  la versión de mongo que manejamos (MongoDB 4.0.27), sin embargo al reemplazar el controlador el error persistió.

Se realizaron pruebas locales para observar el comportamiento y se evidenció que la aplicación permitió conectar con MongoDB cuando la base de datos no estaba de manera segura, sin embargo al iniciar la base de datos de manera segura nuevamente apareció el error, lo que ratifica que el inconveniente era de autenticación.

Siguiendo con la búsqueda otra posible solución era la configuración de los permisos otorgados al usuario creado en la base de datos, sin embargo, el usuario creado era tipo root lo que le da el mayor acceso a privilegios, por ende se descartó esta opción.  

Otra posible solución era actualizar el archivo org.eclipse.birt.data.oda.mongodb.ui-.jar por una versión actualizada, se reemplazó por la versión 4.8.0 que fue la mas reciente encontrada, sin embargo el error persistió.

Realizando todo lo anteriormente mencionado no se logró solucionar el problema de conexión con la base de datos MongoDB.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
